makefile: `solc` depend on `OPENZEPPELIN`  (#20708)
to fix errors like:
```
Error: Source "openzeppelin/contracts/access/Ownable.sol" not found: File not found. Searched the following locations: "/Users/alex/projects/erigon_a2/txnprovider/shutter/internal/contracts/.", "/Users/alex/projects/erigon_a2/txnprovider/shutter/build".
 --> KeyperSet.sol:4:1:
  |
4 | import "openzeppelin/contracts/access/Ownable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```